### ISSUE TITLE
Follow Dockerfile Best Practices

### ISSUE THREAD

**Issue by jspiewak** [rstudio/r-docker#31]
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#sort-multi-line-arguments

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
Specifically "&& rm -rf /var/lib/apt/lists/*", but applied to other OSes and fetched files as well.

Add maintainer labels, e.g. docker@rstudio.com

**Comment by glin** [comment]
Thanks for the suggestions -- #34 will hopefully address these issues.
