### ISSUE TITLE
R-devel versions?

### ISSUE THREAD

**Issue by jimhester** [rstudio/r-docker#39]
It would be useful to have a daily containers built with R-devel, so that we could use them on CI systems and for local testing. Once a day would be more than enough I think. 

CRAN explicitly says that new packages must run R CMD check with R-devel before submission, so this would be something generally useful to (a subset) of customers as well.

Probably requires https://github.com/rstudio/r-builds/issues/6 to be completed first.

**Comment by glin** [comment]
R-devel images are now available and built daily (#59):

```
$ docker run --rm rstudio/r-base:devel-focal R --version

R Under development (unstable) (2020-07-29 r78934) -- "Unsuffered Consequences"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.
```
