### ISSUE TITLE
Set the TZ variable

### ISSUE THREAD

**Issue by jimhester** [rstudio/r-docker#46]
R 3.4 generates a warning during `R CMD check` (it happens whenever `Sys.timezone()` is called) when run under docker

> Warning: running command 'timedatectl' had status 1

However setting the `TZ` environment variable avoids this, e.g. to `UTC`. Is there any chance we could set this automatically for the 3.4 container?

Other versions of R either do not try to call timedatectl, or fail more gracefully if it does not exist, but 3.4 will always generate this warning.

Doing it automatically here would avoid users' running into this if these containers are used in CI settings.

**Comment by glin** [comment]
Thanks for the tip. I ran into this recently trying to load the `anytime` package (and a bunch of other packages that depend on it) on Ubuntu 16 / R 3.4+:
```r
> library(anytime)
Failed to create bus connection: No such file or directory
Warning message:
In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
```

I also noticed that CentOS 6 has a similar issue where you need to configure `TZ` to get `Sys.timezone()` working.
```sh
$ docker run --rm rstudio/r-base:3.1-centos6 R -e 'Sys.timezone()'
> Sys.timezone()
[1] NA

$ docker run --rm rstudio/r-base:3.4-centos6 R -e 'Sys.timezone()'
> Sys.timezone()
Warning: Your system is mis-configured: ‘/etc/localtime’ is not a symlink
Warning: It is strongly recommended to set envionment variable TZ to ‘Etc/UCT’ (or equivalent)
[1] "Etc/UCT"
```

I've opened https://github.com/rstudio/r-docker/pull/48 to set `TZ` to `UTC` for all images.

**Comment by jimhester** [comment]
Great, thanks!
