### ISSUE TITLE
set snapshotted RSPM binaries as default CRAN mirror

### ISSUE THREAD

**Issue by maxheld83** [rstudio/r-docker#55]
expanding on #32 it might be helpful if the images shipped with the appropriate RSPM url, as in `repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/279"` for Ubuntu Bionic, etc.

The rocker images have a neat practice where R releases get CRAN set to `latest` on the MRAN checkpoint server *or* to whatever latest snapshot was taken when, say, R 3.6.3 was still `release`.
This way, even the old images will, by default, "just work" and install the appropriate dependencies.

Though these kinds of black magic do of course increase the complexity.

**Comment by maxheld83** [comment]
an sorry, maybe this belongs in [rstudio/r-builds](https://github.com/rstudio/r-builds)

**Comment by slopp** [comment]
We were trying to avoid too much magic here, especially since there are many folks using these R binaries for on-premise workflows where they actually need to set the repo to their Package Manager instance.

**Comment by maxheld83** [comment]
Thanks!

If anyone else stumbles upon this / might be interested in a container with snapshotted RSPM, I've logged a similar issue over at rocker: https://github.com/rocker-org/rocker/issues/401
